#!/bin/env sh

TMP_PATH='/tmp/humble-lumpia';
RELEASES_URL='https://api.github.com/repos/GloriousEggroll/proton-ge-custom/releases';
STEAM_COMPAT_TOOLS="$HOME/.steam/root/compatibilitytools.d";

getAllReleasesData() {
    curl -s "$RELEASES_URL" | jq '[.[] | { name, published_at, url: .assets[] | select(.content_type == "application/gzip") | .url }] | sort_by(.published_at)'
}

getReleaseData() {
    if test "$1" = "latest"; then
        getAllReleasesData | jq '. | last';
    else
        getAllReleasesData | jq ".[] | select(.name == \"$1\")"
    fi;
}

lsReleases() {
    getAllReleasesData | jq -r '.[].name | select(. != "")';
}

lsInstalled() {
    find "$STEAM_COMPAT_TOOLS"/* -maxdepth 0 -printf '%f\n';
}

downloadRelease() {
    printf "Downloading... ";
    curl -sL "$1" -o "$2";
    echo "Complete!";
}

extractIntoSteam() {
    printf "Extracting... ";
    mkdir -p "$STEAM_COMPAT_TOOLS" && tar -xf "$1" -C ~/.steam/root/compatibilitytools.d/
    echo "Complete!";
}

installRelease() {
    RELEASE_DATA=$(getReleaseData "$1");
    ASSET_URL=$(echo "$RELEASE_DATA" | jq -r '.url');
    DOWNLOAD_URL=$(curl -sL "$ASSET_URL" | jq -r '.browser_download_url');
    DOWNLOAD_NAME=$(echo "$RELEASE_DATA" | jq -r '.name');
    DOWNLOAD_PATH="$TMP_PATH/$DOWNLOAD_NAME";

    mkdir -p "$TMP_PATH" && downloadRelease "$DOWNLOAD_URL" "$DOWNLOAD_PATH" && extractIntoSteam "$DOWNLOAD_PATH";
}

removeRelease() {
    if test -e "$STEAM_COMPAT_TOOLS/$1"; then
        rm -rf "${STEAM_COMPAT_TOOLS:?}/$1";
    else
        echo "The version '$1' is not installed";
    fi;
}

case $1 in
    "ls")
        if test "$2" = "installed"; then
            lsInstalled
        else
            lsReleases
        fi;
    ;;
    "install")
        installRelease "$2"
    ;;
    "rm")
        removeRelease "$2"
    ;;
    *)
        echo "Unrecognized command '$1'";
    ;;
esac
